### ISSUE TITLE
Linux-Brave: Auto skip fails when autoplay is disabled.

### ISSUE THREAD

**Issue by kuraiookami** [ajayyy/SponsorBlock#2056]
I have been using Brave and SponsorBlock together for a while now and until "recently", about a month or so, SponsorBlock has stopped auto-skipping segments completely (it still showed the segments in the seek-bar). I tried resetting the configs, reinstalling the plugin, reinstalling Brave (I forgot to delete the profile now that i think about it) but nothing seamed to fix the issue. Today I tried re-enabling auto-play on a whim and SponsorBlock started working again. I toggled the setting on and off multiple times and can confirm that this is the root cause of the problem. I prefer disabling auto-play to to stop "channel trailers" and other annoying content from auto-playing but this setting breaks things and I don't understand why. 

OS: Ubuntu
Browser: Brave 1.67.123
Extensions:
    SponsorBlock 5.7
    All others have been disabled since I became aware of this bug

**Comment by ajayyy** [comment]
Works fine on my end with Brave on Linux

**Comment by kuraiookami** [comment]
Is there any data I can provide because I can trigger and fix this bug by only changing one setting?

**Comment by raphpa** [comment]
I could see the same behavior today with Brave on Windows on https://www.youtube.com/watch?v=nXRxWm9y3QQ
With autoplay blocked (The browser option to prevent starting videos automatically) for youtube.com the segments were not skipped.

**Comment by uncleanblessing** [comment]
Same here with Brave Version 1.68.128. I can see the chapters and the color codes, but the video just keeps playing.

**Comment by DerEingerostete** [comment]
Same here.
`Specs:
OS: Windows 11 Home 23H2
Browser: Brave Version 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
SponsorBlock Version: 5.7
`

Here are some errors that the console gave me:
`
Error: Extension context invalidated.
    at p.getTitleText (content.js:2:179204)
    at p.render (content.js:2:176456)
    at Na (content.js:2:77467)
    at Ia (content.js:2:77265)
    at Tl (content.js:2:120727)
    at bu (content.js:2:108760)
    at vu (content.js:2:108688)
    at gu (content.js:2:108551)
    at ru (content.js:2:105358)
    at iu (content.js:2:103913)
pa @ content.js:2

content.js:2 Uncaught Error: Extension context invalidated.
    at p.getTitleText (content.js:2:179204)
    at p.render (content.js:2:176456)
    at Na (content.js:2:77467)
    at Ia (content.js:2:77265)
    at Tl (content.js:2:120727)
    at bu (content.js:2:108760)
    at vu (content.js:2:108688)
    at gu (content.js:2:108551)
    at ru (content.js:2:105358)
    at iu (content.js:2:103913)
content.js:2 Uncaught (in promise) Error: Extension context invalidated.
    at Object.videoIDChange (content.js:2:240486)
    at content.js:2:167101
    at Generator.next (<anonymous>)
    at s (content.js:2:164973)

content.js:2 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at content.js:2:241112
    at content.js:2:243517
`

**Comment by ajayyy** [comment]
> Extension context invalidated.

This would imply an extension update just happened which can cause issues until the page reloads
