### ISSUE TITLE
Prevent discord connection issues from crashing the server

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#253]
```
Error: getaddrinfo EAI_AGAIN discordapp.com:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by Joe-Dowd** [comment]
https://github.com/ajayyy/SponsorBlockServer/pull/65
